spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.gate.listenbourg.eu:8080/realms/eFTI_LI

server:
  port: 8072

gate:
  minSleep: 1000
  maxSleep: 2000
  owner: austria eFTI platform
  cda_path: classpath:cda/
  gate: listenbourg
  ap:
    url: http://efti.platform.austria-efti-platform.com:81/domibus/services/wsplugin
    username: austria_efti_platform_service_account
    password: Azerty59*1234567

