spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.gate.austria.eu:8080/realms/eFTI_AT
  datasource:
    url: jdbc:postgresql://reference-gate-shared-db:5432/efti
    username: efti
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8072

gate:
  minSleep: 1000
  maxSleep: 2000
  owner: austria eFTI platform
  cda_path: file:cda/
  gate: austria
  ap:
    url: http://efti.platform.austria-efti-platform.com:81/domibus/services/wsplugin
    username: austria_efti_platform_service_account
    password: Azerty59*1234567

