spring:
  rabbitmq:
    password: li
    username: li
    virtual-host: li
  datasource:
    control:
      liquibase:
        default-schema: eftili
    identifiers:
      liquibase:
        default-schema: eftili
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.gate.listenbourg.eu:8080/realms/eFTI_LI
  jpa:
    properties:
      hibernate:
        control_schema: "eftili"
        identifiers_schema: "eftili"

gate:
  owner: listenbourg
  country: LI
  ap:
    # Domibus is multi-domain: explicitly target the listenbourg domain to ensure PartyId matching uses the correct PMode
    url: http://efti.gate.listenbourg.eu:81/domibus/services/wsPlugin?domain=listenbourg
    username: listenbourg_service_account
    password: Azerty59*1234567
  platforms:
    - platformId: "austria eFTI platform"
      useRestApi: false
