spring:
  rabbitmq:
    password: bo
    username: bo
    virtual-host: bo
  datasource:
    control:
      liquibase:
        default-schema: eftibo
    identifiers:
      liquibase:
        default-schema: eftibo
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.gate.borduria.eu:8080/realms/eFTI_BO
  jpa:
    properties:
      hibernate:
        control_schema: "eftibo"
        identifiers_schema: "eftibo"

gate:
  owner: borduria
  country: BO
  ap:
    # Domibus is multi-domain: explicitly target the borduria domain to ensure PartyId matching uses the correct PMode
    url: http://efti.gate.borduria.eu:81/domibus/services/wsPlugin?domain=borduria
    username: borduria_service_account
    password: Azerty59*1234567
  platforms:
    - platformId: "croatia eFTI platform"
      useRestApi: true
      restApiBaseUrl: "http://platform-ACME:8070/api/gate-api"
