spring:
  rabbitmq:
    password: sy
    username: sy
    virtual-host: sy
  datasource:
    control:
      liquibase:
        default-schema: eftisy
    identifiers:
      liquibase:
        default-schema: eftisy
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.gate.syldavia.eu:8080/realms/eFTI_SY
  jpa:
    properties:
      hibernate:
        control_schema: "eftisy"
        identifiers_schema: "eftisy"

gate:
  owner: syldavia
  country: SY
  ap:
    # Domibus is multi-domain: explicitly target the syldavia domain to ensure PartyId matching uses the correct PMode
    url: http://efti.gate.syldavia.eu:81/domibus/services/wsPlugin?domain=syldavia
    username: syldavia_service_account
    password: Azerty59*1234567
  platforms:
    - platformId: "slovenia eFTI platform"
      useRestApi: false
